const walkAudio = new Audio("audio/walk.wav");
walkAudio.loop = true;
const jumpAudio = new Audio("audio/huch.wav");
const hurtAudio = new Audio("audio/hurt.wav");
const gameOverAudio = new Audio("audio/game-over.wav");
const coinAudio = new Audio("audio/coin.mp3");
const endbossWalkAudio = new Audio("audio/chicken.wav");
endbossWalkAudio.loop = true;
const bottleBreakAudio = new Audio("audio/broken-glass.wav");
